economic_sectors:
  A: "Agriculture, forestry and fishing"
  B: "Mining and quarrying"
  C: "Manufacturing"
  D: "Electricity, gas, steam and air conditioning supply"
  E: "Water supply, sewerage, waste management and remediation activities."
  F: "Construction"
  G: "Wholesale and retail trade; repair of motor vehicles and motorcycles"
  H: "Transportation and storage"
  I: "Accommodation and food service activities"
  J: "Information and communication"
  K: "Financial and insurance activities"
  L: "Real estate activities"
  M: "Professional, scientific and technical activities"
  N: "Administrative and support service activities"
  O: "Public administration and defence; compulsory social security"
  P: "Education"
  Q: "Human health and social work activities"
  R: "Arts, entertainment and recreation"
  S: "Other service activities"
  T: "Activities of households as employers; undifferentiated goods and services - producing activities of households for own use"
  U: "Activities of extraterritorial organizations and bodies"

industries:
  1 : "Agriculture, forestry & fishing (A)"
  2 : "Mining, quarrying & utilities (B,D and E)"
  3 : "Manufacturing (C)"
  4 : "Construction (F)"
  5 : "Motor trades (Part G)"
  6 : "Wholesale (Part G)"
  7 : "Retail (Part G)"
  8 : "Transport & storage (inc postal) (H)"
  9 : "Accommodation & food services (I)"
  10: "Information & communication (J)"
  11: "Financial & insurance (K)"
  12: "Property (L)"
  13: "Professional, scientific & technical (M)"
  14: "Business administration & support services (N)"
  15: "Public administration & defence (O)"
  16: "Education (P)"
  17: "Health (Q)"
  18: "Arts, entertainment, recreation & other services (R,S,T and U)"

conversion:
  "A": 1 # "1 : Agriculture, forestry & fishing (A)"
  "B": 2 # "2 : Mining, quarrying & utilities (B,D and E)"
  "C": 3 # "3 : Manufacturing (C)"
  "D": 2 # "2 : Mining, quarrying & utilities (B,D and E)"
  "E": 2 # "2 : Mining, quarrying & utilities (B,D and E)"
  "F": 4 # "4 : Construction (F)"
  "G":
    - 5 # "5 : Motor trades (Part G)"
    - 6 # "6 : Wholesale (Part G)"
    - 7 # "7 : Retail (Part G)"
  "H": 8 # "8 : Transport & storage (inc postal) (H)"
  "I": 9 # "9 : Accommodation & food services (I)"
  "J": 10 # "10 : Information & communication (J)"
  "K": 11 # "11 : Financial & insurance (K)"
  "L": 12 # "12 : Property (L)"
  "M": 13 # "13 : Professional, scientific & technical (M)"
  "N": 14 # "14 : Business administration & support services (N)"
  "O": 15 # ' 15 : Public administration & defence (O)"
  "P": 16 # "16 : Education (P)"
  "Q": 17 # "17 : Health (Q)"
  "R": 18 # "18 : Arts, entertainment, recreation & other services (R,S,T and U)"
  "S": 18 # "18 : Arts, entertainment, recreation & other services (R,S,T and U)"
  "T": 18 # "18 : Arts, entertainment, recreation & other services (R,S,T and U)"
  "U": 18 # "18 : Arts, entertainment, recreation & other services (R,S,T and U)"

wfh:
    - "I" # "9 : Accommodation & food services (I)"
    - "J" # "10 : Information & communication (J)"
    - "K" # "11 : Financial & insurance (K)"
    - "M" # "13 : Professional, scientific & technical (M)"
    - "N" # "14 : Business administration & support services (N)"
    - "T" # "18 : Arts, entertainment, recreation & other services (R,S,T and U)"



nwp:
    - "F" # "4 : Construction (F)"
    - "G" # 5, 6, 7
    - "H" # "8 : Transport & storage (inc postal) (H)"
    - "S" # "18 : Arts, entertainment, recreation & other services (R,S,T and U)"

dist_conversion:
  "Mainly work from home": [0, 0]
  "Less than 2km": [ 1, 2000 ]
  "2km to less than 5km": [ 2000, 5000 ]
  "5km to less than 10km": [ 5000, 10000 ]
  "10km to less than 20km": [ 10000, 20000 ]
  "20km to less than 30km": [ 20000, 30000 ]
  "30km to less than 40km": [ 30000, 40000 ]
  "40km to less than 60km": [ 40000, 60000 ]
  "60km and over": [ 60000, 80000 ] # We assume nobody travels more than 80km... enjoy life, work locally.
  "Other - No fixed place of work or working outside the UK": NaN